config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  get 'cocktails', to: 'cocktails#index'
  get 'cocktails/new', to: 'cocktails#new'
  post 'cocktails', to: 'cocktails#create'
  get 'cocktails/:id', to: 'cocktails#show', as: 'cocktail'

  get 'cocktails/:cocktail_id/doses/new', to: 'doses#new', as: 'new_cocktail_dose'
  post 'cocktails/:cocktail_id/doses', to: 'doses#create', as: 'cocktail_doses'

  delete 'cocktails/:cocktail_id/doses/:id', to: 'doses#destroy', as: 'dose_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses
  has_many :ingredients, through: :doses

  validates :name, presence: true, uniqueness: true

  before_destroy :destroy_doses

  private

  def destroy_doses
    self.doses.destroy_all
  end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true
  validates :ingredient, presence: true
  validates_uniqueness_of :cocktail, scope: :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses

  validates :name, presence: true, uniqueness: true

  # before_destroy :allow_destroy

  # private

  # def allow_destroy
  #   doses.empty?
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    # @cocktail = Cocktail.find(params[:cocktail_id])
    # @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    # @ingredient = Ingredient.find(params[:dose][:ingredient_id]) unless params[:dose][:ingredient_id] == ""
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    # @dose.ingredient = @ingredient
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.9)), url(https://ritzcarlton-h.assetsadobe.com/is/image/content/dam/the-ritz-carlton/hotels/europe/spain/tenerife-abama/assetmigration/RCABAMA_00236_conversion.png?$XlargeViewport100pct$);">
    <div class="container">
      <h1>FeedCocktail</h1>
      <p>Les meilleures recettes de cocktail Feed</p>
    </div>
  </div>
  <div class="container">
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path cocktail.photo %>)">
          <p><%= cocktail.name %></p>
          <%= link_to "", cocktail_path(cocktail), class: "card-link"%>
        </div>
      </div>
    <% end %>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card-category new-cocktail-card">
        <p>Add a new cocktail !</p>
        <%= link_to "", cocktails_new_path, class: "card-link"%>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add a new cocktail !</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit %>
  <% end %>

</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="card-category-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path @cocktail.photo %>)">
    <div class='text-center'><h1><%= @cocktail.name %></p>
    <% @cocktail.doses.each do |dose| %>
      <p><%= dose.ingredient.name %> : <strong><%= dose.description %></strong>
      <%= link_to "🗑️", dose_destroy_path(@cocktail, dose), method: :delete %></p>
    <% end %>
    </div>
  </div>

  <div class="container">
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :description %>
      <%= f.association :ingredient %>
      <%= f.submit %>
    <% end %>

    <%= link_to "Back to list", cocktails_path, class: 'btn btn-' %>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <h1>Create a new dose !</h1>

  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="#">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" />
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Messages</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>



  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>